In [4]:
import numpy as np
a=np.array([1,5,7,3])
a

array([1, 5, 7, 3])

In [6]:
a[1]

5

In [2]:
import numpy as np
x = np.array([1.0, 2.0])   
x

array([1., 2.])

In [4]:
x.shape

(2,)

In [6]:
x.shape[0]

2

In [8]:
x.shape[1]

IndexError: tuple index out of range

In [10]:
m=x.shape[0]
for i in range(m):
    print(i,x[i])

0 1.0
1 2.0


# Calculate total sales from units and price per unit using matrix multiplication

In [19]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])## each row is an individual unit

In [21]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [29]:
np.dot(price_per_unit,  units)

array([34400, 50000, 64400])

# Basic Calculation

In [2]:
import numpy as np

# Creating a 1D array with 3 elements
x = np.array([1, 2, 3])
print(x)  # Output: [1 2 3]

[1 2 3]


In [4]:
# Creating a 2D array (2 rows, 3 columns)
y = np.array([[1, 2, 3], [4, 5, 6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [44]:
y.size###total number o element

6

In [54]:
np.sqrt(y)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [58]:
np.std(y)###standard deviation

1.707825127659933

In [4]:
# 2x3 array filled with zeros
import numpy as np
z = np.zeros((1, 3))
print(z)

[[0. 0. 0.]]


In [6]:
z = np.zeros((2, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
z = np.zeros((5,2, 3))
print(z)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
# 3x3 array filled with ones
ones_array = np.ones((3, 3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 2x2 array filled with the value 7
full_array = np.full((2, 2), 7)
print(full_array)

[[7 7]
 [7 7]]


***Arrays with Ranges and Steps***

In [26]:
#Arange (Similar to Python's range):
# Array with values from 0 to 9
range_array = np.arange(10)
print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]

# Array with values from 1 to 9 with step of 2
step_array = np.arange(2, 10, 2)
print(step_array)  # Output: [1 3 5 7 9]



[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [32]:
# Array with 5 values evenly spaced between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)  

[0.   0.25 0.5  0.75 1.  ]


**Reshaping Arrays**

In [41]:
# Reshaping a 1D array to a 2D array
original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape(2, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]


In [46]:
reshaped_array.max()

6

In [50]:
reshaped_array.sum(axis=0)## axis=0 means each column

array([5, 7, 9])

In [52]:
reshaped_array.sum(axis=1)## axis=1 means each row

array([ 6, 15])

In [82]:
a=np.array([[2,4,5],[4,1,6],[7,4,1]])
a

array([[2, 4, 5],
       [4, 1, 6],
       [7, 4, 1]])

In [84]:
for row in a:
    print(row)

[2 4 5]
[4 1 6]
[7 4 1]


In [86]:
for cell in a.flat:
    print(cell)

2
4
5
4
1
6
7
4
1


In [92]:
for row in a:
    for cell in row:
     print(cell)

2
4
5
4
1
6
7
4
1


In [104]:
for x in np.nditer(a,order='f'):
 print(x)

2
4
7
4
1
4
5
6
1


In [70]:
a=np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b=np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
np.vstack((a,b))####stack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
np.hstack((a,b))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])