In [207]:
import numpy as np
from keras.datasets import reuters
(xtrain,ytrain),(xtest,ytest)=reuters.load_data(num_words=None,test_split=0.2) 
#load_data means download the data
#num_words=100 means 100 most frequent words from dataset

In [208]:
print('xtrain:',xtrain.shape)
print('xtest:',xtest.shape)

xtrain: (8982,)
xtest: (2246,)


In [209]:
xtrain

array([list([1, 27595, 28842, 8, 43, 10, 447, 5, 25, 207, 270, 5, 3095, 111, 16, 369, 186, 90, 67, 7, 89, 5, 19, 102, 6, 19, 124, 15, 90, 67, 84, 22, 482, 26, 7, 48, 4, 49, 8, 864, 39, 209, 154, 6, 151, 6, 83, 11, 15, 22, 155, 11, 15, 7, 48, 9, 4579, 1005, 504, 6, 258, 6, 272, 11, 15, 22, 134, 44, 11, 15, 16, 8, 197, 1245, 90, 67, 52, 29, 209, 30, 32, 132, 6, 109, 15, 17, 12]),
       list([1, 3267, 699, 3434, 2295, 56, 16784, 7511, 9, 56, 3906, 1073, 81, 5, 1198, 57, 366, 737, 132, 20, 4093, 7, 19261, 49, 2295, 13415, 1037, 3267, 699, 3434, 8, 7, 10, 241, 16, 855, 129, 231, 783, 5, 4, 587, 2295, 13415, 30625, 775, 7, 48, 34, 191, 44, 35, 1795, 505, 17, 12]),
       list([1, 53, 12, 284, 15, 14, 272, 26, 53, 959, 32, 818, 15, 14, 272, 26, 39, 684, 70, 11, 14, 12, 3886, 18, 180, 183, 187, 70, 11, 14, 102, 32, 11, 29, 53, 44, 704, 15, 14, 19, 758, 15, 53, 959, 47, 1013, 15, 14, 19, 132, 15, 39, 965, 32, 11, 14, 147, 72, 11, 180, 183, 187, 44, 11, 14, 102, 19, 11, 123, 186, 90, 67, 960, 4

In [210]:
ytrain[0]

3

In [211]:
xtrain[0]

[1,
 27595,
 28842,
 8,
 43,
 10,
 447,
 5,
 25,
 207,
 270,
 5,
 3095,
 111,
 16,
 369,
 186,
 90,
 67,
 7,
 89,
 5,
 19,
 102,
 6,
 19,
 124,
 15,
 90,
 67,
 84,
 22,
 482,
 26,
 7,
 48,
 4,
 49,
 8,
 864,
 39,
 209,
 154,
 6,
 151,
 6,
 83,
 11,
 15,
 22,
 155,
 11,
 15,
 7,
 48,
 9,
 4579,
 1005,
 504,
 6,
 258,
 6,
 272,
 11,
 15,
 22,
 134,
 44,
 11,
 15,
 16,
 8,
 197,
 1245,
 90,
 67,
 52,
 29,
 209,
 30,
 32,
 132,
 6,
 109,
 15,
 17,
 12]

In [212]:
len(xtrain[0])

87

In [263]:
word_index=reuters.get_word_index()
word_index['flour'] # index o flour is 3025 menas this is the 3025th most frequent word

3025

In [221]:
index_to_word={} # dictionary
for key,value in word_index.items():
    index_to_word[value]=key
index_to_word[3025]

'flour'

In [222]:
## if we want to check what are the full sentences present in xtrain
print(' '.join([index_to_word[x] for x in xtrain[0]])) # at 0th sample of xtrain
print(ytrain[0])

the wattie nondiscriminatory mln loss for plc said at only ended said commonwealth could 1 traders now april 0 a after said from 1985 and from foreign 000 april 0 prices its account year a but in this mln home an states earlier and rise and revs vs 000 its 16 vs 000 a but 3 psbr oils several and shareholders and dividend vs 000 its all 4 vs 000 1 mln agreed largely april 0 are 2 states will billion total and against 000 pct dlrs
3


In [225]:
print(' '.join([index_to_word[x] for x in xtrain[7]])) # at 7th sample of xtrain
print(ytrain[7])

the lt n year reuter trust year an aides weaken reuter 815 unanimously 1987 dlr also vs reuter owned had vs 2 lt from 71 end reuter from banking end an dlrs breakdown m3 reuter billion implemented technically 1987 before were vs reuter 18 which vs some but grains estimated 3 2 an trading div company said alberston's company's said countries 005 000 3 countries' facilitate 000 7 any year april 0 local exchange grains estimated 3 2 an trading company a alberston's most said china's allies 000 3 416 switched 000 7 because year april 0 local pct dlrs
3


In [227]:
from tensorflow.keras.preprocessing.text import Tokenizer
max_words=100 ### from 100 most frequnet words
tokenizer= Tokenizer(num_words=max_words)

In [229]:
### Converting to Matrix
xtrain=tokenizer.sequences_to_matrix(xtrain,mode='binary')
xtest=tokenizer.sequences_to_matrix(xtest,mode='binary')

print('shape of xtrain is : ', xtrain.shape)
print('data in training sample 1:', xtrain[0])
print('lenght odf xtrain: ',len(xtrain[0]))


print('shape of xtest is : ', xtest.shape)




shape of xtrain is :  (8982, 100)
data in training sample 1: [0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0.
 0. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
lenght odf xtrain:  100
shape of xtest is :  (2246, 100)


In [231]:
# in y we need one hot_encoding
from keras.utils import to_categorical
#===num_classess ### y train of how many column

num_classess=46

ytrain=to_categorical(ytrain,num_classess)
ytest=to_categorical(ytest,num_classess)
print(ytrain.shape)
print(ytrain[0])
print(len(ytrain[0]))

(8982, 46)
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
46


# Build RNN Model

In [234]:
xtrain[1] ####### different sample

array([0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [236]:
xtrain.shape[1] #column

100

# RNN takes 3 input Dimension
1.Sample / Sentences / Sequences

** A batch is comprises of one or more samples

2. Time Steps: one time step is one point odf observation in the sample 
3. Features

In [239]:
# Pad seqences
from keras.preprocessing.sequence import pad_sequences
x=[[1,2],[4,8,7],[7,3,9,1]]
print(pad_sequences(x,padding='post'))

[[1 2 0 0]
 [4 8 7 0]
 [7 3 9 1]]


In [296]:
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation,SimpleRNN
from keras import optimizers
from keras.preprocessing.sequence import pad_sequences

## to make equal length we use padding
xtrain=pad_sequences(xtrain,padding='post')
xtest=pad_sequences(xtest,padding='post')

## (sample /// we get from xtrain,timesteps ///////total row,  featres ///////// total column)
xtrain=np.array(xtrain).reshape((xtrain.shape[0],xtrain.shape[1],1))
xtest=np.array(xtest).reshape((xtest.shape[0],xtest.shape[1],1))

def vanilla_rnn():
    model=Sequential()
    model.add(SimpleRNN(50,input_shape=(max_words,1),return_sequences=False)) #50 neuron
                        # for multiple RNN layer return_sequences must be True
    model.add(Dense(num_classess)) #Fully Connected Layer and in final layer we have the define classess of y
    model.add(Activation('softmax'))
    model.summary()

    adam=optimizers.Adam(learning_rate=0.001) ## optimizer does on the basis of error it will update the weight
    model.compile(loss='categorical_crossentropy',optimizer=adam,metrics=['accuracy'])

    return model


In [298]:
## Calling the model
import tensorflow as tf
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier


model= KerasClassifier(build_fn=vanillarnn,epoch=5,batch_size=50)
model.fit(xtrain,ytrain)

ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'

In [300]:
# pip install scikeras


In [302]:
from scikeras.wrappers import KerasClassifier

In [304]:
model= KerasClassifier(build_fn=vanilla_rnn,epochs=5,batch_size=50)
model.fit(xtrain,ytrain)

C:\Users\ASUS\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 46)             │         2,346 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_3 (Activation)       │ (None, 46)             │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,946 (19.32 KB)

 Trainable params: 4,946 (19.32 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
180/180 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.3047 - loss: 2.8412
Epoch 2/5
180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.3662 - loss: 2.3898
Epoch 3/5
180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.4069 - loss: 2.2305
Epoch 4/5
180/180 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.4212 - loss: 2.2168
Epoch 5/5
180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3885 - loss: 2.2898


C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\_tags.py:354: FutureWarning: The KerasClassifier or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

KerasClassifier(
	model=None
	build_fn=<function vanilla_rnn at 0x00000193FBEB05E0>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=50
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=5
	class_weight=None
)

In [308]:
from sklearn.metrics import accuracy_score
# y_pred=model.predict(xtest)
y_pred = np.argmax(model.predict(xtest), axis=1)
y_test=np.argmax(ytest,axis=1)

print("Accuracy:", accuracy_score( y_pred,y_test))

45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Accuracy: 0.44746215494211933


# RNN on Custom DATAset

***TAsk isto classify the reveiw in Positive(1) and Negetive(0)*** 

In [606]:
import pandas as pd
df=pd.read_csv('yelp_labelled.csv',usecols=[0,1],names=['Sentences','label'])

df.head(6)

Sentences label
0                           Wow... Loved this place.     1
1                                 Crust is not good.     0
2          Not tasty and the texture was just nasty.     0
3  Stopped by during the late May bank holiday of...     1
4  The selection on the menu was great and so wer...     1
5     Now I am getting angry and I want my damn pho.     0

In [608]:
x=df['Sentences']
y=df['label']
# Ensure labels are numeric (convert to integers)
y = pd.to_numeric(y, errors='coerce')

# Drop rows with invalid labels
valid_indices = ~y.isna()
x = x[valid_indices]
y = y[valid_indices].astype(int)  # Ensure integer type

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [610]:
print(xtrain.shape,xtest.shape)

(562,) (141,)


In [612]:
xtrain

842      the potatoes were great and so was the biscuit.
45     The only thing I did like was the prime rib an...
204                    Service is friendly and inviting.
667                     A fantastic neighborhood gem !!!
15     I was shocked because no signs indicate cash o...
                             ...                        
447    The chicken wings contained the driest chicken...
851              Worst food/service I've had in a while.
36                       Ample portions and good prices.
947                        But then they came back cold.
304                              The food was very good.
Name: Sentences, Length: 562, dtype: object

In [614]:
print(xtrain[1])
print(ytrain[1])

Crust is not good.
0


### converting Words into Numbers through Embedding/Tokenizer

In [617]:
## Basically creating a word to Indexdictionary
from tensorflow.keras.preprocessing.text import Tokenizer
max_words=1000 ### from 1000 most frequnet words
tokenizer= Tokenizer(num_words=max_words,lower=True)
tokenizer.fit_on_texts(xtrain)

xtrain=tokenizer.texts_to_sequences(xtrain)
xtest=tokenizer.texts_to_sequences(xtest)

#print('shape of xtrain is : ', xtrain.shape)
print('data in training sample 1:', xtrain[1])






data in training sample 1: [1, 68, 236, 3, 56, 34, 4, 1, 498, 499, 2, 237, 500]


In [619]:
print(xtrain[1])
print(ytrain[1])

[1, 68, 236, 3, 56, 34, 4, 1, 498, 499, 2, 237, 500]
0


In [621]:
from keras.preprocessing.sequence import pad_sequences
maxlen=100 #we set the maximum size of each list to 100.
## to make equal length we use padding
xtrain=pad_sequences(xtrain,padding='post',maxlen=maxlen)
xtest=pad_sequences(xtest,padding='post',maxlen=maxlen)
print(xtrain[1])

[  1  68 236   3  56  34   4   1 498 499   2 237 500   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]


In [623]:
print(xtrain[1,:]) ## row, upto last column

[  1  68 236   3  56  34   4   1 498 499   2 237 500   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]


In [625]:
# Hot_Encoding on Y
from keras.utils import to_categorical
#===num_classess ### y train of how many column

num_classess=2 ## positive / negetive

ytrain=to_categorical(ytrain,num_classess)
ytest=to_categorical(ytest,num_classess)

print("ytrain shape:", ytrain.shape)
print("ytrain sample:", ytrain[0])
print("Length of one-hot encoded label:", len(ytrain[0]))

ytrain shape: (562, 2)
ytrain sample: [0. 1.]
Length of one-hot encoded label: 2


In [627]:
# RNN Model
from keras.models import Sequential
from keras.layers import Dense,Dropout,Activation,SimpleRNN
from keras import optimizers


## (sample /// we get from xtrain,timesteps ///////total row,  featres ///////// total column)
xtrain=np.array(xtrain).reshape((xtrain.shape[0],xtrain.shape[1],1))
xtest=np.array(xtest).reshape((xtest.shape[0],xtest.shape[1],1))
print(xtrain.shape) ### 3D
print(xtest.shape)


(562, 100, 1)
(141, 100, 1)


In [633]:
num_classess=2
def vanilla_rnn():
    model=Sequential()
    model.add(SimpleRNN(50,input_shape=(maxlen,1),return_sequences=False)) #50 neuron
                        # for multiple RNN layer return_sequences must be True
    model.add(Dense(num_classess)) #Fully Connected Layer and in final layer we have the define classess of y
    model.add(Activation('softmax'))
    model.summary()

    adam=optimizers.Adam(learning_rate=0.001) ## optimizer does on the basis of error it will update the weight
    model.compile(loss='categorical_crossentropy',optimizer=adam,metrics=['accuracy'])

    return model

In [635]:
from scikeras.wrappers import KerasClassifier
model= KerasClassifier(build_fn=vanilla_rnn,epochs=5,batch_size=50)
model.fit(xtrain,ytrain)

C:\Users\ASUS\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\ASUS\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │           102 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 2)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,702 (10.55 KB)

 Trainable params: 2,702 (10.55 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4998 - loss: 0.7026
Epoch 2/5
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5364 - loss: 0.6918
Epoch 3/5
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5136 - loss: 0.6931
Epoch 4/5
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4916 - loss: 0.6958
Epoch 5/5
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5207 - loss: 0.6987


C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\utils\_tags.py:354: FutureWarning: The KerasClassifier or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


AttributeError: 'super' object has no attribute '__sklearn_tags__'

AttributeError: 'super' object has no attribute '__sklearn_tags__'

KerasClassifier(
	model=None
	build_fn=<function vanilla_rnn at 0x000001938779B4C0>
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=50
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=5
	class_weight=None
)

In [643]:
from sklearn.metrics import accuracy_score
#y_pred=model.predict(xtest)
y_pred = np.argmax(model.predict(xtest), axis=1)
y_test=np.argmax(ytest,axis=1)

print("Accuracy:", accuracy_score(y_pred, y_test))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Accuracy: 0.46808510638297873


# Testing moDEL ON NEW iNPUT


In [658]:
a=['i love their services']
a=tokenizer.texts_to_sequences(a)
a=np.array(a)
a=pad_sequences(a,padding='post',maxlen=maxlen)
a=a.reshape((a.shape[0],a.shape[1],1))
print(a.shape)
prediction=model.predict(a)
print(prediction) # 1 means positive.ekta pabo

(1, 100, 1)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[1 0]]
