In [11]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [12]:
one_hot("amazing restaurant",30)## assigning both the number within given range which is one_hot

[13, 2]

In [13]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)
# For each review assigning one_hot

[[23, 4], [13, 2], [21, 26], [25, 8, 14], [18, 19, 17], [8, 4], [23, 19, 10], [17, 1], [17, 1], [21, 3]]


In [14]:
## we need Padding
# As some sentences are 2 long, some are 3

In [15]:

max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
#padding='post' means pad towards the end i.e Null value are Zero
print(padded_reviews)

[[23  4  0]
 [13  2  0]
 [21 26  0]
 [25  8 14]
 [18 19 17]
 [ 8  4  0]
 [23 19 10]
 [17  1  0]
 [17  1  0]
 [21  3  0]]


In [16]:
embeded_vector_size = 5 ## each word embedding e Total koita row takbe

In [17]:
## Creating The Model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embeded_vector_size, input_length=max_length, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [18]:
X = padded_reviews
y = sentiment # y hocche label ta

In [19]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
# Force the model to build its layers
model(X)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.51010543],
       [0.50265807],
       [0.51621526],
       [0.47949958],
       [0.5013802 ],
       [0.50464183],
       [0.5077199 ],
       [0.509639  ],
       [0.509639  ],
       [0.5214521 ]], dtype=float32)>

In [21]:
# Display model summary
print(model.summary()) ## Flattened e 5+5+5=15 hbe

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (10, 3, 5)             │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (10, 15)               │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (10, 1)                │            16 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 166 (664.00 B)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [22]:
model.fit(X, y, epochs=50, verbose=0)

In [23]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 1.0000 - loss: 0.6383


1.0

*** here Sentiment Classification is a fake prblm....we are more interseted in Word Embedding***

In [26]:
weights = model.get_layer('embedding').get_weights()[0] ## name e jeita disilam
weights ## last flatenned er ager ta

array([[-6.30297186e-03,  8.66672862e-03,  4.24369127e-02,
         2.25556716e-02, -6.92835748e-02],
       [-4.18578796e-02, -7.26459995e-02, -5.22229187e-02,
         3.32167149e-02,  6.31412119e-02],
       [ 1.26968632e-02,  7.39025185e-03,  7.11449459e-02,
        -6.80604503e-02, -3.57362069e-02],
       [-1.02594923e-02, -6.90874085e-02, -9.51282214e-04,
         1.00640811e-01,  1.77235696e-02],
       [-4.76588681e-02,  1.20300967e-02, -1.37776192e-02,
        -3.78633700e-02,  6.09877286e-03],
       [ 3.70550863e-02, -9.81239229e-03,  3.69916447e-02,
        -4.09912840e-02,  1.86406076e-04],
       [-4.64183576e-02, -1.11075863e-02,  2.43441202e-02,
         3.61228846e-02,  2.00755931e-02],
       [-2.48012301e-02,  4.63892482e-02, -3.23586017e-02,
        -2.49051452e-02, -2.65301112e-02],
       [-1.32312281e-02,  3.45810018e-02,  8.09113160e-02,
         5.55642284e-02, -4.40980643e-02],
       [-3.36884148e-02, -4.16931733e-02, -4.58751321e-02,
         1.85298361e-02

In [27]:
len(weights) ## equalto vocabulary size

30

#################################################################

# ############################

# Word2Vector Implementation using Gensim Library(Mainly use in NLP)

In [4]:
#!pip install gensim

In [5]:
#!pip install python-Levenshtein

In [11]:
import gensim
import pandas as pd

# Reading and Exploring the Dataset
The dataset we are using here is a subset of Amazon reviews from the Cell Phones & Accessories category. The data is stored as a JSON file and can be read using pandas.

Link to the Dataset: http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Cell_Phones_and_Accessories_5.json.gz

In [13]:
df = pd.read_json("Cell_Phones_and_Accessories_5.json", lines=True)
df

reviewerID        asin       reviewerName helpful  \
0       A30TL5EWN6DFXT  120401325X          christina  [0, 0]   
1        ASY55RVNIL0UD  120401325X           emily l.  [0, 0]   
2       A2TMXE2AFO7ONB  120401325X              Erica  [0, 0]   
3        AWJ0WZQYMYFQ4  120401325X                 JM  [4, 4]   
4        ATX7CZYFXI1KW  120401325X   patrice m rogoza  [2, 3]   
...                ...         ...                ...     ...   
194434  A1YMNTFLNDYQ1F  B00LORXVUE    eyeused2loveher  [0, 0]   
194435  A15TX8B2L8B20S  B00LORXVUE       Jon Davidson  [0, 0]   
194436  A3JI7QRZO1QG8X  B00LORXVUE  Joyce M. Davidson  [0, 0]   
194437  A1NHB2VC68YQNM  B00LORXVUE     Nurse Farrugia  [0, 0]   
194438  A1AG6U022WHXBF  B00LORXVUE     Trisha Crocker  [0, 0]   

                                               reviewText  overall  \
0       They look good and stick good! I just don't li...        4   
1       These stickers work like the review says they ...        5   
2       These are awesome and make my phone look so st...        5   
3       Item arrived in great time and was in perfect ...        4   
4       awesome! stays on, and looks great. can be use...        5   
...                                                   ...      ...   
194434  Works great just like my original one. I reall...        5   
194435  Great product. Great packaging. High quality a...        5   
194436  This is a great cable, just as good as the mor...        5   
194437  I really like it becasue it works well with my...        5   
194438  product as described, I have wasted a lot of m...        5   

                                                  summary  unixReviewTime  \
0                                              Looks Good      1400630400   
1                                   Really great product.      1389657600   
2                                          LOVE LOVE LOVE      1403740800   
3                                                   Cute!      1382313600   
4               leopard home button sticker for iphone 4s      1359849600   
...                                                   ...             ...   
194434                           This works just perfect!      1405900800   
194435           Great replacement cable. Apple certified      1405900800   
194436                                       Real quality      1405900800   
194437  I really like it becasue it works well with my...      1405814400   
194438              I have wasted a lot of money on cords      1405900800   

         reviewTime  
0       05 21, 2014  
1       01 14, 2014  
2       06 26, 2014  
3       10 21, 2013  
4        02 3, 2013  
...             ...  
194434  07 21, 2014  
194435  07 21, 2014  
194436  07 21, 2014  
194437  07 20, 2014  
194438  07 21, 2014  

[194439 rows x 9 columns]

In [14]:
# now we are going to train a Word2vvec Model using only the reviewText Column

In [15]:

df.shape

(194439, 9)

In [16]:
df.reviewText

0         They look good and stick good! I just don't li...
1         These stickers work like the review says they ...
2         These are awesome and make my phone look so st...
3         Item arrived in great time and was in perfect ...
4         awesome! stays on, and looks great. can be use...
                                ...                        
194434    Works great just like my original one. I reall...
194435    Great product. Great packaging. High quality a...
194436    This is a great cable, just as good as the mor...
194437    I really like it becasue it works well with my...
194438    product as described, I have wasted a lot of m...
Name: reviewText, Length: 194439, dtype: object

In [17]:
df.reviewText[0]

"They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up and it was irritating. I just won't buy a product like this again"

here we have to do the pre-possing like lower-order sentences;removing the punctuation mark and so on

this can easily be done using the Gensim Library

In [20]:
gensim.utils.simple_preprocess("They look good and stick good! I just don't like the rounded shape because I was always bumping it and Siri kept popping up ")

['they',
 'look',
 'good',
 'and',
 'stick',
 'good',
 'just',
 'don',
 'like',
 'the',
 'rounded',
 'shape',
 'because',
 'was',
 'always',
 'bumping',
 'it',
 'and',
 'siri',
 'kept',
 'popping',
 'up']

In [21]:
# gensim.utils.simple_preprocess it is a prebuilt function basically Tiokenizing it

In [22]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

0         [they, look, good, and, stick, good, just, don...
1         [these, stickers, work, like, the, review, say...
2         [these, are, awesome, and, make, my, phone, lo...
3         [item, arrived, in, great, time, and, was, in,...
4         [awesome, stays, on, and, looks, great, can, b...
                                ...                        
194434    [works, great, just, like, my, original, one, ...
194435    [great, product, great, packaging, high, quali...
194436    [this, is, great, cable, just, as, good, as, t...
194437    [really, like, it, becasue, it, works, well, w...
194438    [product, as, described, have, wasted, lot, of...
Name: reviewText, Length: 194439, dtype: object

#########################################################

Gensim is an NLP library and it comes with Word2vec class

In [24]:
## Training the Model
model = gensim.models.Word2Vec(
    window=10,## here Window=10 means 10 words before/after ur Target Words
    min_count=2,## min_count =2is at least need 2 word for training
    workers=4,## workers is how many CPU threads is needed to train the model
)

In [25]:
#Build Vocabulary
model.build_vocab(review_text, progress_per=1000)

In [27]:
model.corpus_count### how many examples we have

194439

In [28]:
model.epochs## by Default eto dewa

5

In [29]:
###Train the Word2Vec Model
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(61501232, 83868975)

# Save the Model
Save the model so that it can be reused in other applications

In [31]:
model.save("./word2vec-amazon-cell-accessories-reviews-short.model")

# Evaluating
Finding Similar Words and Similarity between words

In [33]:
model.wv.most_similar("bad")

[('terrible', 0.7004721760749817),
 ('shabby', 0.6529711484909058),
 ('horrible', 0.6155804991722107),
 ('good', 0.5861226916313171),
 ('weird', 0.5269432663917542),
 ('awful', 0.5240021347999573),
 ('poor', 0.5232263803482056),
 ('mad', 0.5222101211547852),
 ('okay', 0.5203279256820679),
 ('funny', 0.5189719200134277)]

*Checking Similarity Score*

In [35]:
model.wv.similarity(w1="cheap", w2="inexpensive")

0.5391328

In [36]:
model.wv.similarity(w1="great", w2="good")

0.7860492

In [55]:
model.wv.similarity(w1="great", w2="great")

1.0

# Exercise
Train a word2vec model on the Sports & Outdoors Reviews Dataset Once you train a model on this, find the words most similar to 'awful' and find similarities between the following word tuples: ('good', 'great'), ('slow','steady')

In [61]:
import gensim
import pandas as pd

In [65]:
df = pd.read_json("Sports_and_Outdoors_5.json", lines=True)
df

reviewerID        asin  \
0         AIXZKN4ACSKI  1881509818   
1       A1L5P841VIO02V  1881509818   
2        AB2W04NI4OEAD  1881509818   
3       A148SVSWKTJKU6  1881509818   
4        AAAWJ6LW9WMOO  1881509818   
...                ...         ...   
296332  A2XX2A4OJCDNLZ  B00LFPS0CY   
296333  A3LGT6UZL99IW1  B00LFPS0CY   
296334   ASKZO80Z1RKTR  B00LFPS0CY   
296335   APRNS6DB68LLV  B00LFPS0CY   
296336  A3UJRNI8UR4871  B00LFPS0CY   

                                            reviewerName helpful  \
0                                           David Briner  [0, 0]   
1                                        Jason A. Kramer  [1, 1]   
2                                             J. Fernald  [2, 2]   
3                         Jusitn A. Watts "Maverick9614"  [0, 0]   
4                                           Material Man  [0, 0]   
...                                                  ...     ...   
296332                               RatherLiveInKeyWest  [2, 3]   
296333  Richard C. Drew "Anaal Nathra/Uthe vas Bethod...  [0, 0]   
296334                                         Robin Lee  [0, 0]   
296335                  Rob Slaven "slavenrm@gmail. com"  [1, 1]   
296336                               Wulfstan "wulfstan"  [2, 2]   

                                               reviewText  overall  \
0       This came in on time and I am veru happy with ...        5   
1       I had a factory Glock tool that I was using fo...        5   
2       If you don't have a 3/32 punch or would like t...        4   
3       This works no better than any 3/32 punch you w...        4   
4       I purchased this thinking maybe I need a speci...        4   
...                                                   ...      ...   
296332  This is a water bottle done right. It is a ver...        5   
296333  If you're looking for an insulated water bottl...        5   
296334  This Hydracentials Sporty 25 OZ, double insula...        5   
296335  As usual I received this item free in exchange...        5   
296336  Hydracentials insulated 25 oz water bottle.Thi...        5   

                                                  summary  unixReviewTime  \
0                                          Woks very good      1390694400   
1                       Works as well as the factory tool      1328140800   
2                               It's a punch, that's all.      1330387200   
3                         It's a punch with a Glock logo.      1328400000   
4                 Ok,tool does what a regular punch does.      1366675200   
...                                                   ...             ...   
296332  Hydracentials Sporty 25 Oz Stainless Steel Wat...      1405036800   
296333          Large, incredibly well made water bottle!      1405641600   
296334             "Great Water Bottle For Hot Day"......      1405900800   
296335  A pretty impressive water bottle.  Best I've s...      1405900800   
296336                                     "Cool" Bottle!      1405382400   

         reviewTime  
0       01 26, 2014  
1        02 2, 2012  
2       02 28, 2012  
3        02 5, 2012  
4       04 23, 2013  
...             ...  
296332  07 11, 2014  
296333  07 18, 2014  
296334  07 21, 2014  
296335  07 21, 2014  
296336  07 15, 2014  

[296337 rows x 9 columns]

In [67]:
df.shape

(296337, 9)

In [69]:
review_text = df.reviewText.apply(gensim.utils.simple_preprocess)
review_text

0         [this, came, in, on, time, and, am, veru, happ...
1         [had, factory, glock, tool, that, was, using, ...
2         [if, you, don, have, punch, or, would, like, t...
3         [this, works, no, better, than, any, punch, yo...
4         [purchased, this, thinking, maybe, need, speci...
                                ...                        
296332    [this, is, water, bottle, done, right, it, is,...
296333    [if, you, re, looking, for, an, insulated, wat...
296334    [this, hydracentials, sporty, oz, double, insu...
296335    [as, usual, received, this, item, free, in, ex...
296336    [hydracentials, insulated, oz, water, bottle, ...
Name: reviewText, Length: 296337, dtype: object

In [71]:
## Training the Model
model = gensim.models.Word2Vec(
    window=20,## here Window=10 means 10 words before/after ur Target Words
    min_count=2,## min_count =2is at least need 2 word for training
    workers=4,## workers is how many CPU threads is needed to train the model
)

In [73]:
model.build_vocab(review_text, progress_per=1000)

In [75]:
model.train(review_text, total_examples=model.corpus_count, epochs=10)

(182680031, 242993070)

In [77]:
model.save("./Sports_and_Outdoors_5.model")

In [79]:
model.wv.most_similar("awful")

[('terrible', 0.6925578117370605),
 ('horrible', 0.6728781461715698),
 ('poor', 0.5704731345176697),
 ('overpowering', 0.5527158379554749),
 ('unacceptable', 0.550285816192627),
 ('crappy', 0.54129958152771),
 ('ugly', 0.5367524027824402),
 ('stupid', 0.5298815369606018),
 ('utter', 0.5289550423622131),
 ('sad', 0.5264509320259094)]

In [81]:
model.wv.similarity(w1="good", w2="great")

0.7698795

In [83]:
model.wv.similarity(w1="slow", w2="steady")

0.42195684